import './chose-button.scss'
import './chose-button__button.scss'
import './chose-button__label.scss'
import './chose-button__title.scss'
import './chose-button__flex-direction_column.scss'
import './chose-button__container.scss'
import './chose-button_margin-left_20px.scss'