import './review.scss'
import './review__person.scss'
import './review__person-avatar.scss'
import './review__person-about.scss'
import './review__person-name.scss'
import './review__person-info.scss'
import './review__review.scss'
import './review__text.scss'