import './fonts/fonts.scss'
import  '../node_modules/item-quantity-dropdown/lib/item-quantity-dropdown.min.js'
import '../node_modules/item-quantity-dropdown/lib/item-quantity-dropdown.min.css'
import '../node_modules/air-datepicker/air-datepicker.css'

import './blocks/toggle/toggle.js'
import './blocks/like-button/like-button.js'
import './blocks/range-slider/range-slider.js'
import './blocks/dropdown/dropdown.js'
import './blocks/checkbox-list/checkbox-list.js'
import './blocks/color/color.js'
import './blocks/form-elements/form-elements.js'
import './blocks/input/input.js'
import './blocks/chose-button/chose-button.js'
import './blocks/button/button.js'
import './blocks/footer1/footer1.js'
import './blocks/material-icons/material-icons.js'
import './blocks/logo/logo.js'
import './blocks/menu/menu.js'
import './blocks/rate-button/rate-button.js'
import './blocks/text/text.js'
import './blocks/title-block/title-block.js'
import './blocks/pagination/pagination.js'
import './blocks/ui-kit/ui-kit.js'
import './blocks/rich-checkbox-button/rich-checkbox-button.js'
import './blocks/bullet-list/bullet-list.js'
import './blocks/advantage/advantage.js'
import './blocks/review/review.js'
import './blocks/date-dropdown/date-dropdown.js'
import './blocks/find-room/find-room.js'
import './blocks/cards/cards.js'
import './blocks/colors-and-type/colors-and-type.js'

import './blocks/header/header.scss'

import './blocks/expand-more/expand-more.scss'
import './blocks/expand-more/expand-more__margin-left.scss'

import './blocks/footer2/footer2.scss'
import './blocks/footer2/footer2__rights.scss'

import './blocks/contacts/contacts.scss'
import './blocks/contacts/contacts__margin.scss'
