import './fonts/fonts.scss'
import  '../node_modules/item-quantity-dropdown/lib/item-quantity-dropdown.min.js'
import '../node_modules/item-quantity-dropdown/lib/item-quantity-dropdown.min.css'

import './blocks/toggle/toggle.js'
import './blocks/like-button/like-button.js'
import './blocks/range-slider/range-slider.js'
import './blocks/dropdown/dropdown.js'
import './blocks/checkbox-list/checkbox-list.js'

import './blocks/color/color__example_background_green.scss'
import './blocks/color/color__example_background_purple.scss'
import './blocks/color/color__example_background_dark-shade-100.scss'
import './blocks/color/color__example_background_dark-shade-75.scss'
import './blocks/color/color__example_background_dark-shade-50.scss'
import './blocks/color/color__example_background_dark-shade-25.scss'
import './blocks/color/color__example_background_dark-shade-5.scss'
import './blocks/color/color__description.scss'
import './blocks/color/color__body.scss'
import './blocks/color/color.scss'

import './blocks/column-colors/column-colors.scss'
import './blocks/column-colors/column-colors__body.scss'

import './blocks/column-text/column-text.scss'
import './blocks/column-text/column-text__body.scss'

import './blocks/ui-kit/ui-kit.scss'

import './blocks/colors-and-type/colors-and-type.scss'

import './blocks/text/text.scss'
import './blocks/text/text__body.scss'
import './blocks/text/text__description.scss'
import './blocks/text/text__example.scss'

import './blocks/header/header.scss'
import './blocks/header/header__body.scss'

import './blocks/logo/logo.scss'
import './blocks/logo/logo__body.scss'
import './blocks/logo/logo__img.scss'
import './blocks/logo/logo__text.scss'

import './blocks/menu/menu.scss'
import './blocks/menu/menu__list.scss'
import './blocks/menu/menu__item.scss'
import './blocks/menu/menu__link.scss'
import './blocks/menu/menu__line.scss'
import './blocks/menu/menu__link_bold.scss'

import './blocks/expand-more/expand-more.scss'
import './blocks/expand-more/expand-more__margin-left.scss'

import './blocks/button/button.scss'
import './blocks/button/button_color_white.scss'
import './blocks/button/button_color_blue.scss'
import './blocks/button/button_background-color_white.scss'
import './blocks/button/button_background-color_blue.scss'
import './blocks/button/button_border_blue.scss'
import './blocks/button/button_border_none.scss'
import './blocks/button/button_width_small.scss'
import './blocks/button/button_width_medium.scss'
import './blocks/button/button_width_big.scss'
import './blocks/button/button_height_small.scss'
import './blocks/button/button_height_big.scss'
import './blocks/button/button_opacity_50per.scss'
import './blocks/button/button_border-opacity_50per.scss'
import './blocks/button/button_color_dark.scss'

import './blocks/footer1/footer1.scss'
import './blocks/footer1/footer1__logo.scss'
import './blocks/footer1/footer1__description.scss'
import './blocks/footer1/footer1__nav-head.scss'
import './blocks/footer1/footer1__nav-item.scss'
import './blocks/footer1/footer1__top.scss'
import './blocks/footer1/footer1__bottom.scss'
import './blocks/footer1/footer1__nav_width_18.scss'
import './blocks/footer1/footer1__nav-subscribe.scss'
import './blocks/footer1/footer1__input.scss'
import './blocks/footer1/footer1__nav.scss'
import './blocks/footer1/footer1__rights.scss'

import './blocks/footer2/footer2.scss'
import './blocks/footer2/footer2__rights.scss'

import './blocks/input/input.scss'
import './blocks/input/input__text.scss'
import './blocks/input/input__form.scss'
import './blocks/input/input__submit.scss'
import './blocks/input/input__header.scss'
import './blocks/input/input__title.scss'
import './blocks/input/input__state.scss'
import './blocks/input/input__margin_top_20.scss'
import './blocks/input/input__margin_left_20.scss'
import './blocks/input/input__width_small.scss'
import './blocks/input/input__width_medium.scss'
import './blocks/input/input__width_big.scss'

import './blocks/contacts/contacts.scss'
import './blocks/contacts/contacts__margin.scss'

import './blocks/form-elements/form-elements.scss'
import './blocks/form-elements/form-elements__block.scss'
import './blocks/form-elements/form-elements__column.scss'
import './blocks/form-elements/form-elements__date.scss'
import './blocks/form-elements/form-elements__title.scss'
import './blocks/form-elements/form-elements__flex.scss'
import './blocks/form-elements/form-elements__title-description.scss'

import './blocks/chose-button/chose-button.scss'
import './blocks/chose-button/chose-button__button.scss'
import './blocks/chose-button/chose-button__label.scss'
import './blocks/chose-button/chose-button__title.scss'
import './blocks/chose-button/chose-button__flex-direction_column.scss'
import './blocks/chose-button/chose-button__container.scss'

import './blocks/toggle/toggle.scss'
import './blocks/toggle/toggle__input.scss'
import './blocks/toggle/toggle__switch.scss'
import './blocks/toggle/toggle__text.scss'
import './blocks/toggle/toggle_active.scss'
import './blocks/toggle/toggle__switch_active.scss'
import './blocks/toggle/toggle__form.scss'

import './blocks/like-button/like-button.scss'
import './blocks/like-button/like-button__button.scss'
import './blocks/like-button/like-button__number.scss'
import './blocks/like-button/like-button__button_active.scss'
import './blocks/like-button/like-button__number_active.scss'

import './blocks/material-icons/material-icons__favorite.scss'
import './blocks/material-icons/material-icons__favorite-border.scss'
import './blocks/material-icons/material-icons__star.scss'
import './blocks/material-icons/material-icons__star-border.scss'
import './blocks/material-icons/material-icons__arrow-forward.scss'

import './blocks/rate-button/rate-button.scss'
import './blocks/rate-button/rate-button__button.scss'
import './blocks/rate-button/rate-button_margin-left_20.scss'

import './blocks/range-slider/range-slider.scss'
import './blocks/range-slider/range-slider__head.scss'
import './blocks/range-slider/range-slider__title.scss'
import './blocks/range-slider/range-slider__slider.scss'
import './blocks/range-slider/range-slider__range.scss'

import './blocks/title-block/title-block.scss'
import './blocks/title-block/title-block_margin-bottom_16px.scss'
import './blocks/title-block/title-block_margin-top_40px.scss'

import './blocks/pagination/pagination.scss'
import './blocks/pagination/pagination__button.scss'
import './blocks/pagination/pagination__button_active.scss'
import './blocks/pagination/pagination__next-button.scss'
import './blocks/pagination/pagination__text.scss'
import './blocks/pagination/pagination__form.scss'
import './blocks/pagination/pagination__button_inactive.scss'

import './blocks/dropdown/dropdown.scss'

import './blocks/checkbox-list/checkbox-list.scss'
import './blocks/checkbox-list/checkbox-list__text.scss'