import './sign-up.scss'
import './sign-up__row.scss'
import './sign-up__column.scss'
import './sign-up__row_margin-top_40px.scss'
import './sign-up__row_margin-top_30px.scss'
import './sign-up__row_margin-top_20px.scss'
import './sign-up__row_margin-top_10px.scss'
import './sign-up__row_justify-content_flex-start.scss'